# Adapted from https://github.com/vega/vega/blob/4b945e22905c610ccc2bdd28471a6f1f80aa1636/.github/workflows/test.yml
name: Test (monorepo)
on:
  push:
    branches:
    - main
    - keller-mark/pnpm-incremental-2
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        node: [16, 18]
        os: [ubuntu-20.04]
        include:
          - os: windows-2022
            node: 16
    
    name: Test on ${{ matrix.os }} with Node ${{ matrix.node }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: |
            - recursive: true
              cwd: 'monorepo'
      - run: pnpm test
      - run: pnpm build